### ISSUE TITLE
Zap failed on FUSE vault

### ISSUE THREAD

**Issue by ILayZ** [beefyfinance/beefy-contracts#170]
Hi!
I used to zap FUSE to ELON-FUSE LP, but now tx wants 9,5 mln gas and failed
https://explorer.fuse.io/tx/0x4817536145ba4ecdbf34ab0b42b6df31ce366f0212957b87fcfe3650b94a197e/internal-transactions
previos tx
https://explorer.fuse.io/tx/0x7bf560f77b4326f6b8385d5fc574199e4ae5244014d9a1b844027738844b38a1/token-transfers

Probably other vaults affected as well.
Plz, fix this.

**Comment by devyJo** [comment]
Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the [Support live chat](https://beefysupport.com/) below for instant support response [Support chat](https://beefysupport.com/) 

Note: Click on the live chat icon at the bottom corner of the page to start a conversation      @ILayZ
